name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-18.04

    strategy:
      fail-fast: false
      matrix:
        language: [ 'python' ]
        # CodeQL supports [ 'cpp', 'csharp', 'go', 'java', 'javascript', 'python' ]
        # Learn more:
        # https://docs.github.com/en/free-pro-team@latest/github/finding-security-vulnerabilities-and-errors-in-your-code/configuring-code-scanning#changing-the-languages-that-are-analyzed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install prerequisites
      run: |
        python -m pip install --upgrade pip
        pip install -U -f https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04 wxPython==4.1.0
        pip install wheel coveralls
        pip install -r requirements.txt
    
    - name: Run unit test
      run: |
        xvfb-run --auto-servernum python -m coverage run --source=asn1editor -m unittest discover
        python -m coverage html -d coverage
        
    - name: Upload test results
      uses: actions/upload-artifact@v2
      with:
          name: coverage-report
          path: coverage/index.html
          
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 asn1editor --config max-line-length=160
